### ISSUE TITLE
missing runtime in container: libGL.so.1

### ISSUE THREAD

**Issue by truatpasteurdotfr** [truatpasteurdotfr/docker-miniconda3-Ot2Rec-Savu#2]
```
$ singularity build docker-miniconda3-ot2rec-savu.sif  docker://ghcr.io/truatpasteurdotfr/docker-miniconda3-ot2rec-savu:main
$ singularity shell docker-miniconda3-ot2rec-savu.sif
Apptainer> eval "$(conda shell.bash hook)"
Apptainer> conda activate o2r_savu
(o2r_savu) Apptainer> python -c 'import savu; import Ot2Rec'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/Ot2Rec/src/Ot2Rec/__init__.py", line 19, in <module>
    from . import motioncorr
  File "/opt/Ot2Rec/src/Ot2Rec/motioncorr.py", line 26, in <module>
    from . import magicgui as mgMod
  File "/opt/Ot2Rec/src/Ot2Rec/magicgui.py", line 52, in <module>
    no_mdoc=False,
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/magicgui/_magicgui.py", line 251, in inner_func
    return magic_class(func, **kwargs)
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/magicgui/widgets/_function_gui.py", line 185, in __init__
    widgets=list(sig.widgets(app).values()),
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/magicgui/signature.py", line 237, in widgets
    {n: p.to_widget(app) for n, p in self.parameters.items()}
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/magicgui/signature.py", line 237, in <dictcomp>
    {n: p.to_widget(app) for n, p in self.parameters.items()}
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/magicgui/signature.py", line 149, in to_widget
    raise_on_unknown=self.raise_on_unknown,
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/magicgui/widgets/_bases/create_widget.py", line 85, in create_widget
    _app = use_app(kwargs.pop("app"))
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/magicgui/application.py", line 164, in use_app
    return _use_app()
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/magicgui/application.py", line 154, in _use_app
    Application._instance = Application(backend_name)
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/magicgui/application.py", line 37, in __init__
    self._use(backend_name)
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/magicgui/application.py", line 63, in _use
    self._backend_module = import_module(f"magicgui.backends.{module_name}")
  File "/opt/conda/envs/o2r_savu/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/magicgui/backends/_qtpy/__init__.py", line 1, in <module>
    from .application import ApplicationBackend
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/magicgui/backends/_qtpy/application.py", line 4, in <module>
    from qtpy.QtWidgets import QApplication
  File "/opt/conda/envs/o2r_savu/lib/python3.7/site-packages/qtpy/QtWidgets.py", line 22, in <module>
    from PyQt5.QtWidgets import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by truatpasteurdotfr** [comment]
[main b42b898] OS required packages
